In [1]:
def test():
    print('test()for function')
    return
test()

test()for function


In [2]:
class demo:
    def test(self):
        print("test()for the class and method")
        return
obj=demo()
obj.test()
 

test()for the class and method


In [3]:
class demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=demo1()
print(p1.fact(5))

120


In [8]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def add(self,p1,p2):
        return p1+p2
c1=demo2(10,20)
print(c1.add(100,200))

300


In [9]:
class person(object):
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
    
class employee(person):
        def isemployee(self):
            return True
        
emp=person("Anil")
print(emp.getname(),emp.isemployee())
    
emp1=employee("Akhil")
print(emp1.getname(),emp1.isemployee())

Anil False
Akhil True


In [10]:
lst=[1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [12]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)


[1 2 3 4]


In [14]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [16]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [17]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [18]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [20]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [21]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [22]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [23]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [26]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row: ",a1[0])

first row:  [1 2 3]


In [27]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row: ",a1[1][1])



second row:  5


In [28]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [29]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicingrow coloum :",a1[:,1])



slicingrow coloum : [2 5]


In [30]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value=",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))

[3.92453063 4.52005545 5.36111115 5.82627603 6.47172327 5.82610529
 6.12104402 5.87653124 4.6073211  4.66299512]
min value= 3.924530626212127
max value= 6.4717232681025365
mean value= 5.319769329342066
median value= 5.593608222199984


In [34]:
c1 = np.array([1,2])
c2 = np.array([4,5])
np.dot(c1,c2)


14

In [36]:
c1 = np.array([(1,2),(3,4)])
c2 = np.array([(4,5),(1,2)])
np.dot(c1,c2)

array([[ 6,  9],
       [16, 23]])

In [54]:
import pandas as pd
dict1 ={"name":["anil","akhil","dinesh","harsha","ajay","krathi"],
      "emailid":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsh@gmail.com","ajay@gmail.com","krathi@gmail.com"],
      "mobilenumber":[888,999,7777,444,4545465,245547],
      "address":["hyd","hyd","hyd","hyd","hyd","hyd"]}


b=pd.DataFrame(dict1)
print(b)

     name           emailid  mobilenumber address
0    anil    anil@gmail.com           888     hyd
1   akhil   akhil@gmail.com           999     hyd
2  dinesh  dinesh@gmail.com          7777     hyd
3  harsha   harsh@gmail.com           444     hyd
4    ajay    ajay@gmail.com       4545465     hyd
5  krathi  krathi@gmail.com        245547     hyd
